spring:
  profiles:
    active: dev

server:
    tomcat:
        uri-encoding: UTF-8

# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ myBatisPlus配置 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ #
mybatis-plus:
  ## mapper.xml文件路径
  mapper-locations: classpath*:/mappers/**/*.xml
  ## 实体包
  type-aliases-package: com.leigq.www.mybatisplusstudy.domain.entity
  ## 配置
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true